### ISSUE TITLE
Project don't build

### ISSUE THREAD

**Issue by hannesa2** [spokestack/spokestack-tray-android#22]
This repo has same bad state like the other repo https://github.com/spokestack/app-actions-example/issues/1

![image](https://user-images.githubusercontent.com/3314607/115102918-493e0980-9f4e-11eb-85fe-00f5bd979553.png)

I recommend to protect main branch and only do pull requests with CI build.

**Comment by hannesa2** [comment]
see #25

**Comment by hannesa2** [comment]
You deleted `SpokestackTray/src/main/java/io/spokestack/tray/VoicePrompt.kt` in 9db0b9813b81325

I feel a little bit as your QA

**Comment by space-pope** [comment]
My apologies on this one. I'm in the middle of a bigger change, and main got unstable between releases because I forgot to cherry-pick changes from the example app. Main is a protected branch.
