### ISSUE TITLE
I see SSL errors

### ISSUE THREAD

**Issue by hannesa2** [spokestack/spokestack-tray-android#29]
I still see on Pixel 4 with Android 11
![image](https://user-images.githubusercontent.com/3314607/115108078-d09b7500-9f6e-11eb-8318-59488d987e02.png)

But it seams to work. At least it listens and response 👍

**Comment by space-pope** [comment]
Well, at least it's not inconsistent between the different repositories. I'll have to keep an eye on it, as I haven't been able to reproduce.
